## LLaVA 7B
llava-v1.5-7b:
    model_name: llava-v1.5
    model_dir: /path/to/your/model/
    gen_kwargs:
        max_new_tokens: 512
        min_new_tokens: 1
        do_sample: false
        temperature: 0.0